base:
  project: mlops-project
  random_state: 42
  target_col: median_house_value

data_source:
  gd_source: training_data/housing.csv

load_data:
  raw_dataset_csv: data/raw/housing.csv

vis_data:
  profiling_path: reports/figures/eda/profiling.html

prepro_data:
  prepro_train: data/processed/train_housing_pre.npy
  prepro_test: data/processed/test_housing_pre.npy
  pipeline_path: models/pipeline

split_data:
  train_path: data/processed/train_housing.csv
  test_path: data/processed/test_housing.csv
  test_size: 0.2
  n_splits: 1

estimators:
  LinearRegression:
    cross_val_cv: 5
  RandomForestReg:
    param_grid:
      n_estimators:
      - 3
      - 10
      - 30
      max_features:
      - 2
      - 4
      - 5
      - 8

model_dir: models

reports:
  params: reports/params.json
  linreg_cross_val_scores: reports/linreg_cross_val_scores.json
  linreg_eval_scores: reports/linreg_eval_scores.json
  test_scores: reports/test_scores.json

webapp_model_dir: prediction_service/model/model.joblib