base:
  project: mlops-project
  random_state: 42
  target_col: median_house_value

data_source:
  gd_source: training_data/housing.csv

load_data:
  raw_dataset_csv: data/raw/housing.csv

vis_data:
  profiling_path: reports/figures/eda/profiling.html

split_data:
  train_path: data/processed/train_housing.csv
  test_path: data/processed/test_housing.csv
  test_size: 0.2
  n_splits: 1

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib